// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard_repo.go
//
// Generated by this command:
//
//	mockgen -source=dashboard_repo.go -destination=mocks/dashboard_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dbgen "assignment-ptes-achmad-rifai/internal/shared/database/dbgen"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetProductReport mocks base method.
func (m *MockRepository) GetProductReport(ctx context.Context) (dbgen.GetProductDashboardReportRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductReport", ctx)
	ret0, _ := ret[0].(dbgen.GetProductDashboardReportRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductReport indicates an expected call of GetProductReport.
func (mr *MockRepositoryMockRecorder) GetProductReport(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductReport", reflect.TypeOf((*MockRepository)(nil).GetProductReport), ctx)
}

// GetRecentProducts mocks base method.
func (m *MockRepository) GetRecentProducts(ctx context.Context, limit int32) ([]dbgen.GetRecentProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentProducts", ctx, limit)
	ret0, _ := ret[0].([]dbgen.GetRecentProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentProducts indicates an expected call of GetRecentProducts.
func (mr *MockRepositoryMockRecorder) GetRecentProducts(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentProducts", reflect.TypeOf((*MockRepository)(nil).GetRecentProducts), ctx, limit)
}

// GetTopCustomers mocks base method.
func (m *MockRepository) GetTopCustomers(ctx context.Context, limit int32) ([]dbgen.GetTopCustomersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCustomers", ctx, limit)
	ret0, _ := ret[0].([]dbgen.GetTopCustomersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCustomers indicates an expected call of GetTopCustomers.
func (mr *MockRepositoryMockRecorder) GetTopCustomers(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCustomers", reflect.TypeOf((*MockRepository)(nil).GetTopCustomers), ctx, limit)
}
