// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard_service.go
//
// Generated by this command:
//
//	mockgen -source=dashboard_service.go -destination=mocks/dashboard_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	dashboard "assignment-ptes-achmad-rifai/internal/dashboard"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetCompleteDashboard mocks base method.
func (m *MockService) GetCompleteDashboard(ctx context.Context, limit int32) (dashboard.DashboardReportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompleteDashboard", ctx, limit)
	ret0, _ := ret[0].(dashboard.DashboardReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompleteDashboard indicates an expected call of GetCompleteDashboard.
func (mr *MockServiceMockRecorder) GetCompleteDashboard(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompleteDashboard", reflect.TypeOf((*MockService)(nil).GetCompleteDashboard), ctx, limit)
}

// GetProductDashboard mocks base method.
func (m *MockService) GetProductDashboard(ctx context.Context) (dashboard.ProductReportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductDashboard", ctx)
	ret0, _ := ret[0].(dashboard.ProductReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductDashboard indicates an expected call of GetProductDashboard.
func (mr *MockServiceMockRecorder) GetProductDashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductDashboard", reflect.TypeOf((*MockService)(nil).GetProductDashboard), ctx)
}

// GetTopCustomers mocks base method.
func (m *MockService) GetTopCustomers(ctx context.Context, limit int32) ([]dashboard.TopCustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCustomers", ctx, limit)
	ret0, _ := ret[0].([]dashboard.TopCustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCustomers indicates an expected call of GetTopCustomers.
func (mr *MockServiceMockRecorder) GetTopCustomers(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCustomers", reflect.TypeOf((*MockService)(nil).GetTopCustomers), ctx, limit)
}
