// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dbgen

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const getProductDashboardReport = `-- name: GetProductDashboardReport :one
SELECT 
    COUNT(*) AS total_products,
    CAST(IFNULL(SUM(stock_quantity), 0) AS SIGNED) AS total_stock,
    CAST(IFNULL(AVG(price), 0) AS DECIMAL(10,2)) AS avg_price
FROM 
    products
`

type GetProductDashboardReportRow struct {
	TotalProducts int64           `json:"total_products"`
	TotalStock    int64           `json:"total_stock"`
	AvgPrice      decimal.Decimal `json:"avg_price"`
}

func (q *Queries) GetProductDashboardReport(ctx context.Context) (GetProductDashboardReportRow, error) {
	row := q.queryRow(ctx, q.getProductDashboardReportStmt, getProductDashboardReport)
	var i GetProductDashboardReportRow
	err := row.Scan(&i.TotalProducts, &i.TotalStock, &i.AvgPrice)
	return i, err
}

const getRecentProducts = `-- name: GetRecentProducts :many
SELECT 
    id, name, price, stock_quantity, created_at
FROM 
    products
ORDER BY 
    created_at DESC
LIMIT ?
`

type GetRecentProductsRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Price         decimal.Decimal `json:"price"`
	StockQuantity int32           `json:"stock_quantity"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) GetRecentProducts(ctx context.Context, limit int32) ([]GetRecentProductsRow, error) {
	rows, err := q.query(ctx, q.getRecentProductsStmt, getRecentProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentProductsRow
	for rows.Next() {
		var i GetRecentProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.StockQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
