// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countProductsStmt, err = db.PrepareContext(ctx, countProducts); err != nil {
		return nil, fmt.Errorf("error preparing query CountProducts: %w", err)
	}
	if q.createCategoryStmt, err = db.PrepareContext(ctx, createCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCategory: %w", err)
	}
	if q.createCustomerStmt, err = db.PrepareContext(ctx, createCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCustomer: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.deleteCategoryStmt, err = db.PrepareContext(ctx, deleteCategory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCategory: %w", err)
	}
	if q.deleteCustomerStmt, err = db.PrepareContext(ctx, deleteCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCustomer: %w", err)
	}
	if q.deleteProductStmt, err = db.PrepareContext(ctx, deleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProduct: %w", err)
	}
	if q.getCategoriesStmt, err = db.PrepareContext(ctx, getCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategories: %w", err)
	}
	if q.getCategoryByIDStmt, err = db.PrepareContext(ctx, getCategoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByID: %w", err)
	}
	if q.getCustomerByIDStmt, err = db.PrepareContext(ctx, getCustomerByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomerByID: %w", err)
	}
	if q.getCustomersStmt, err = db.PrepareContext(ctx, getCustomers); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomers: %w", err)
	}
	if q.getProductByIDStmt, err = db.PrepareContext(ctx, getProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductByID: %w", err)
	}
	if q.listProductsStmt, err = db.PrepareContext(ctx, listProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListProducts: %w", err)
	}
	if q.updateCategoryStmt, err = db.PrepareContext(ctx, updateCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCategory: %w", err)
	}
	if q.updateCustomerStmt, err = db.PrepareContext(ctx, updateCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCustomer: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countProductsStmt != nil {
		if cerr := q.countProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsStmt: %w", cerr)
		}
	}
	if q.createCategoryStmt != nil {
		if cerr := q.createCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCategoryStmt: %w", cerr)
		}
	}
	if q.createCustomerStmt != nil {
		if cerr := q.createCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCustomerStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.deleteCategoryStmt != nil {
		if cerr := q.deleteCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCategoryStmt: %w", cerr)
		}
	}
	if q.deleteCustomerStmt != nil {
		if cerr := q.deleteCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCustomerStmt: %w", cerr)
		}
	}
	if q.deleteProductStmt != nil {
		if cerr := q.deleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductStmt: %w", cerr)
		}
	}
	if q.getCategoriesStmt != nil {
		if cerr := q.getCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoriesStmt: %w", cerr)
		}
	}
	if q.getCategoryByIDStmt != nil {
		if cerr := q.getCategoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByIDStmt: %w", cerr)
		}
	}
	if q.getCustomerByIDStmt != nil {
		if cerr := q.getCustomerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomerByIDStmt: %w", cerr)
		}
	}
	if q.getCustomersStmt != nil {
		if cerr := q.getCustomersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomersStmt: %w", cerr)
		}
	}
	if q.getProductByIDStmt != nil {
		if cerr := q.getProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductByIDStmt: %w", cerr)
		}
	}
	if q.listProductsStmt != nil {
		if cerr := q.listProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsStmt: %w", cerr)
		}
	}
	if q.updateCategoryStmt != nil {
		if cerr := q.updateCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCategoryStmt: %w", cerr)
		}
	}
	if q.updateCustomerStmt != nil {
		if cerr := q.updateCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCustomerStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	countProductsStmt   *sql.Stmt
	createCategoryStmt  *sql.Stmt
	createCustomerStmt  *sql.Stmt
	createProductStmt   *sql.Stmt
	deleteCategoryStmt  *sql.Stmt
	deleteCustomerStmt  *sql.Stmt
	deleteProductStmt   *sql.Stmt
	getCategoriesStmt   *sql.Stmt
	getCategoryByIDStmt *sql.Stmt
	getCustomerByIDStmt *sql.Stmt
	getCustomersStmt    *sql.Stmt
	getProductByIDStmt  *sql.Stmt
	listProductsStmt    *sql.Stmt
	updateCategoryStmt  *sql.Stmt
	updateCustomerStmt  *sql.Stmt
	updateProductStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		countProductsStmt:   q.countProductsStmt,
		createCategoryStmt:  q.createCategoryStmt,
		createCustomerStmt:  q.createCustomerStmt,
		createProductStmt:   q.createProductStmt,
		deleteCategoryStmt:  q.deleteCategoryStmt,
		deleteCustomerStmt:  q.deleteCustomerStmt,
		deleteProductStmt:   q.deleteProductStmt,
		getCategoriesStmt:   q.getCategoriesStmt,
		getCategoryByIDStmt: q.getCategoryByIDStmt,
		getCustomerByIDStmt: q.getCustomerByIDStmt,
		getCustomersStmt:    q.getCustomersStmt,
		getProductByIDStmt:  q.getProductByIDStmt,
		listProductsStmt:    q.listProductsStmt,
		updateCategoryStmt:  q.updateCategoryStmt,
		updateCustomerStmt:  q.updateCustomerStmt,
		updateProductStmt:   q.updateProductStmt,
	}
}
