// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbgen

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, customer_id, total_quantity, total_price, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ID            string          `json:"id"`
	CustomerID    string          `json:"customer_id"`
	TotalQuantity int32           `json:"total_quantity"`
	TotalPrice    decimal.Decimal `json:"total_price"`
	CreatedAt     time.Time       `json:"created_at"`
}

// Sqlc Query
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.exec(ctx, q.createOrderStmt, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.TotalQuantity,
		arg.TotalPrice,
		arg.CreatedAt,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (id, order_id, product_id, quantity, unit_price)
VALUES (?, ?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	ID        string          `json:"id"`
	OrderID   string          `json:"order_id"`
	ProductID string          `json:"product_id"`
	Quantity  int32           `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.exec(ctx, q.createOrderItemStmt, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = ?
`

func (q *Queries) DeleteOrder(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteOrderStmt, deleteOrder, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, total_quantity, total_price, created_at 
FROM orders 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.queryRow(ctx, q.getOrderByIDStmt, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TotalQuantity,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, product_id, quantity, unit_price
FROM order_items
WHERE order_id = ?
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.query(ctx, q.getOrderItemsByOrderIDStmt, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrders = `-- name: GetOrders :many
SELECT id, customer_id, total_quantity, total_price, created_at 
FROM orders 
ORDER BY created_at DESC
`

func (q *Queries) GetOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.query(ctx, q.getOrdersStmt, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.TotalQuantity,
			&i.TotalPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
