// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const countProducts = `-- name: CountProducts :one
SELECT
    COUNT(DISTINCT p.id) AS total
FROM
    products p
WHERE
    (
        ? = ''
        OR p.name LIKE CONCAT ('%', ?, '%')
    )
    AND (
        ? = ''
        OR p.category_id = ?
    )
    AND (
        ? = 0
        OR p.price >= ?
    )
    AND (
        ? = 0
        OR p.price <= ?
    )
    AND (
        ? = 0
        OR p.stock_quantity >= ?
    )
    AND (
        ? = 0
        OR p.stock_quantity <= ?
    )
`

type CountProductsParams struct {
	SearchName interface{}     `json:"search_name"`
	CategoryID string          `json:"category_id"`
	MinPrice   decimal.Decimal `json:"min_price"`
	MaxPrice   decimal.Decimal `json:"max_price"`
	MinStock   int32           `json:"min_stock"`
	MaxStock   int32           `json:"max_stock"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.queryRow(ctx, q.countProductsStmt, countProducts,
		arg.SearchName,
		arg.SearchName,
		arg.CategoryID,
		arg.CategoryID,
		arg.MinPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MaxPrice,
		arg.MinStock,
		arg.MinStock,
		arg.MaxStock,
		arg.MaxStock,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO
    products (
        id,
        name,
        description,
        price,
        category_id,
        stock_quantity,
        is_active
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Description   sql.NullString  `json:"description"`
	Price         decimal.Decimal `json:"price"`
	CategoryID    string          `json:"category_id"`
	StockQuantity int32           `json:"stock_quantity"`
	IsActive      bool            `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.exec(ctx, q.createProductStmt, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
		arg.StockQuantity,
		arg.IsActive,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE
    id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock_quantity,
    p.is_active,
    p.created_at,
    p.updated_at,
    c.id AS category_id,
    c.name AS category_name,
    c.description AS category_description
FROM
    products p
    JOIN categories c ON c.id = p.category_id
WHERE
    p.id = ?
LIMIT
    1
`

type GetProductByIDRow struct {
	ID                  string          `json:"id"`
	Name                string          `json:"name"`
	Description         sql.NullString  `json:"description"`
	Price               decimal.Decimal `json:"price"`
	StockQuantity       int32           `json:"stock_quantity"`
	IsActive            bool            `json:"is_active"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	CategoryID          string          `json:"category_id"`
	CategoryName        string          `json:"category_name"`
	CategoryDescription sql.NullString  `json:"category_description"`
}

func (q *Queries) GetProductByID(ctx context.Context, id string) (GetProductByIDRow, error) {
	row := q.queryRow(ctx, q.getProductByIDStmt, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryDescription,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.name,
    p.description,
    p.price,
    p.stock_quantity,
    p.is_active,
    p.created_at,
    c.id AS category_id,
    c.name AS category_name,
    CAST(IFNULL (SUM(oi.quantity), 0) AS UNSIGNED) AS total_sold
FROM
    products p
    JOIN categories c ON c.id = p.category_id
    LEFT JOIN order_items oi ON oi.product_id = p.id
WHERE
    (
        ? = ''
        OR p.name LIKE CONCAT ('%', ?, '%')
    )
    AND (
        ? = ''
        OR p.category_id = ?
    )
    AND (
        ? = 0
        OR p.price >= ?
    )
    AND (
        ? = 0
        OR p.price <= ?
    )
    AND (
        ? = 0
        OR p.stock_quantity >= ?
    )
    AND (
        ? = 0
        OR p.stock_quantity <= ?
    )
GROUP BY
    p.id,
    c.id
ORDER BY
    CASE
        WHEN ? = 'sold_desc' THEN IFNULL (SUM(oi.quantity), 0)
    END DESC,
    p.created_at DESC
LIMIT
    ?
OFFSET
    ?
`

type ListProductsParams struct {
	SearchName interface{}     `json:"search_name"`
	CategoryID string          `json:"category_id"`
	MinPrice   decimal.Decimal `json:"min_price"`
	MaxPrice   decimal.Decimal `json:"max_price"`
	MinStock   int32           `json:"min_stock"`
	MaxStock   int32           `json:"max_stock"`
	OrderBy    interface{}     `json:"order_by"`
	Limit      int32           `json:"limit"`
	Offset     int32           `json:"offset"`
}

type ListProductsRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Description   sql.NullString  `json:"description"`
	Price         decimal.Decimal `json:"price"`
	StockQuantity int32           `json:"stock_quantity"`
	IsActive      bool            `json:"is_active"`
	CreatedAt     time.Time       `json:"created_at"`
	CategoryID    string          `json:"category_id"`
	CategoryName  string          `json:"category_name"`
	TotalSold     int64           `json:"total_sold"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts,
		arg.SearchName,
		arg.SearchName,
		arg.CategoryID,
		arg.CategoryID,
		arg.MinPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MaxPrice,
		arg.MinStock,
		arg.MinStock,
		arg.MaxStock,
		arg.MaxStock,
		arg.OrderBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQuantity,
			&i.IsActive,
			&i.CreatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.TotalSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET
    name = ?,
    description = ?,
    price = ?,
    category_id = ?,
    stock_quantity = ?,
    is_active = ?
WHERE
    id = ?
`

type UpdateProductParams struct {
	Name          string          `json:"name"`
	Description   sql.NullString  `json:"description"`
	Price         decimal.Decimal `json:"price"`
	CategoryID    string          `json:"category_id"`
	StockQuantity int32           `json:"stock_quantity"`
	IsActive      bool            `json:"is_active"`
	ID            string          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.exec(ctx, q.updateProductStmt, updateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
		arg.StockQuantity,
		arg.IsActive,
		arg.ID,
	)
	return err
}
